### ISSUE TITLE
能不能接入某个图库啊，设置一下分类，只有一张图感觉太干了。。。。

### ISSUE THREAD

**Issue by Anson365** [FantasticMao/ycy-intellij-plugin#13]
RT

**Comment by hujian0923** [comment]
刚想过来提这个issues的，结果发现被抢了

**Comment by FantasticMao** [comment]
@Anson365 我觉得接入图库并不是一个很好的主意，因为：
1. 无法保证图库接口的稳定性；
2. 下载图片可能会花费时间，造成卡顿；

但是我觉得配置本地的多张图片是个不错的主意，有空我支持一下

**Comment by Anson365** [comment]
可以暴露图库的API啊，使用方自己去配置，加载不出来的话，日志警告一下，然后默认加载本地缓存的。不知道这样怎么样

**Comment by hujian0923** [comment]
能不能随机切换图片啊，远程随机切换

**Comment by Anson365** [comment]
> @Anson365 我觉得接入图库并不是一个很好的主意，因为：
> 
> 1. 无法保证图库接口的稳定性；
> 2. 下载图片可能会花费时间，造成卡顿；
> 
> 但是我觉得配置本地的多张图片是个不错的主意，有空我支持一下

可以暴露图库的API啊，使用方自己去配置，加载不出来的话，日志警告一下，然后默认加载本地缓存的。不知道这样怎么样

**Comment by SoledadVac** [comment]
就想问下，女程序员用什么。。。

**Comment by ruixiang-lai** [comment]
我也想说，功能太单一了点，起码多张图片轮换，可以播放视频最佳了，能自己上传就好了

**Comment by FantasticMao** [comment]
@Anson365 @hujian0923 @ruixiang-lai 加了个配置多张图片的功能，各位可以更新插件试用一下

@SoledadVac 可以把图片、换成你的男神
