### ISSUE TITLE
phpstorm不能用啊，没有找到设置的地方

### ISSUE THREAD

**Issue by baagee** [FantasticMao/ycy-intellij-plugin#15]
phpstorm不能用啊，没有找到设置的地方

**Comment by FantasticMao** [comment]
配置功能是在 1.2 版本加上的，我中午才上传 1.2 版本到 jetbrains 插件仓库。

现在布拉格时间是 09:43，等 jetbrains 工作人员上班再审核，估计还要一会儿

**Comment by FantasticMao** [comment]
@baagee 图片和时间的配置功能已经上线了，在 IDEA 中更新一下插件就好
