### ISSUE TITLE
更新之后报错了，Mac系统

### ISSUE THREAD

**Issue by celverbamboo** [FantasticMao/ycy-intellij-plugin#17]
大佬你看一下吧

**Comment by celverbamboo** [comment]
![image](https://user-images.githubusercontent.com/24216880/56558481-778fe500-65d1-11e9-9ddf-50492973dc28.png)

**Comment by FantasticMao** [comment]
日志说你安装的 [OnlineSearch](https://plugins.jetbrains.com/plugin/8298-onlinesearch) 插件报错了，这个异常和「超越鼓励师」插件没有关系 🙃
