### ISSUE TITLE
不能只有杨超越，最好可配置鼓励师

### ISSUE THREAD

**Issue by celverbamboo** [FantasticMao/ycy-intellij-plugin#8]

**Comment by FantasticMao** [comment]
@celverbamboo 谢谢你的建议～

图片和时间的配置功能，我打算在这周末实现，还请耐心等待几天😄

**Comment by celverbamboo** [comment]
希望是一个求组，然后顺序播放，或者随机播放


发自我的 iPhone

**Comment by ojbk-666** [comment]
不如提醒的时候从网上获取个段子，而不仅仅是那点文字[手动滑稽~]

**Comment by celverbamboo** [comment]
兄弟搞定了吗？想用了呢

**Comment by cyixlq** [comment]
比如可以自己配置些鼓励师，像麻生希，小野寺梨纱，麻仓优等等

**Comment by FantasticMao** [comment]
@celverbamboo 进度可以查看这个分支 https://github.com/FantasticMao/ycy-intellij-plugin/tree/v1.2 。基本功能写完了，这两天测试一下版本的兼容性，然后就提审核🙃

**Comment by FantasticMao** [comment]
@celverbamboo @ojbk-666 @cyixlq 图片和时间的配置功能已经上线了，在 IDEA 中更新一下插件就好
